language: c
sudo: required
services:
  - docker

install:
  - docker build --rm -t buildenv docker/

script:
  >
    set -ex;
    docker run -t --rm -v $(pwd):/io sh -c 'set -e; for INTERP in /opt/*/bin/python; do $INTERP /io/manylinux1-check; done';
    PACKAGES=(numpy);
    for pkg in "${PACKAGES[@]}"; do
      docker run -t --rm -v `pwd`:/io buildenv /opt/3.5/bin/pip install --no-binary :all: ${pkg} -vv;
    done
