language: c
sudo: required
services:
  - docker

install:
  - docker build --rm -t manylinux1_i686 -f docker/Dockerfile-i686 docker/
  - docker build --rm -t manylinux1_x86_64 -f docker/Dockerfile-x86_64 docker/

script:
  >
    set -ex;
    docker run -t --rm -v $(pwd):/io manylinux1_x86_64 sh -c 'set -e; for INTERP in /opt/*/bin/python; do $INTERP /io/manylinux1-check.py; done';
    docker run -t --rm -v $(pwd):/io manylinux1_i686 sh -c 'set -e; for INTERP in /opt/*/bin/python; do $INTERP /io/manylinux1-check.py; done';
